### ISSUE TITLE
Synchronous or asynchronous I2C?

### ISSUE THREAD

**Issue by fivdi** [eltoroit/eltoroit.github.io#5]
To the best of my knowledge all of the rpio functions called in the [readValue function](https://github.com/eltoroit/eltoroit.github.io/blob/master/S03_ADC_LED_RPIO.js#L13-L23) are blocking synchronous functions. On the other hand, the readValue function is declared as an async function which implies that it runs asynchronous. If my assumption about rpio functions being synchronous is correct, readValue shouldn't be declared as an async function as it will mislead the reader into thinking that synchronous code is asynchronous.

**Comment by eltoroit** [comment]
@fivdi thanks for pointing this out. I have fixed the code and updated the repo (and the blog).

**Comment by eltoroit** [comment]
I decided to go with RPIO because your npm package did not include I2C. There is a note at the bottom of the documentation pointing out to another npm package [i2c-bus](https://github.com/fivdi/i2c-bus).

My first impression was that [PIGPIO](https://www.npmjs.com/package/pigpio) did not bother to do I2C and I was disappointed, but then I realized that you are also the author of [i2c-bus](https://github.com/fivdi/i2c-bus). I imagine you split the two packages in order to avoid bloating [PIGPIO](https://www.npmjs.com/package/pigpio).

The more I read about your package(s), the more I like them!

I will be writing a second article that uses the ADC with your  [i2c-bus](https://github.com/fivdi/i2c-bus) package.

Thanks for the awesome code!
